### ISSUE TITLE
Criação de painel iterativo

### ISSUE THREAD

**Issue by VerasNp** [brunosaunders/Metodos-Numericos-I#17]

**Comment by brunosaunders** [comment]
Especificação:
![image](https://github.com/brunosaunders/Metodos-Numericos-I/assets/66584326/1b131ed8-6aab-4ccf-b563-acdde5f2cc74)
**Possível interação**
![image](https://github.com/brunosaunders/Metodos-Numericos-I/assets/66584326/71240f49-bbd7-414f-8293-8e48bf3cab47)
**Outra interação a partir da tela inicial**
![image](https://github.com/brunosaunders/Metodos-Numericos-I/assets/66584326/04e8f3dc-d1fb-417d-a3ac-87903607e682)

A estrutura de dados para armazenar as funções deve ser `std::vector<NewtonRaphson> funcoes` onde todos elementos vão implementar um método para printar suas informações conforme mostrado no segundo caso
