### ISSUE TITLE
Com coeficientes fixos,  gerar quadro comparativo dos métodos

### ISSUE THREAD

**Issue by israelnicolas940** [brunosaunders/Metodos-Numericos-I#7]

**Comment by brunosaunders** [comment]
Colunas da tabela:
![image](https://github.com/brunosaunders/Metodos-Numericos-I/assets/66584326/01b8432b-6dea-42a6-a449-a078e97b9caa)

Ideia para gerar a tabela:
![image](https://github.com/brunosaunders/Metodos-Numericos-I/assets/66584326/e2c5bd96-6b4d-42e7-ad48-409749c39094)

**Comment by israelnicolas940** [comment]
O e2 acho que é só |f(x_k)| não?
